datasource:
    postgres:
      host: ${POSTGRES_HOST}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      port: ${POSTGRES_PORT}

    mysql:
      host: ${MYSQL_HOST}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      port: ${MYSQL_PORT}